### ISSUE TITLE
通过pip install -U delta-task包里面无法导入pandas等库函数

### ISSUE THREAD

**Issue by Dyson-c** [delta-mpc/delta-task#13]
![image](https://user-images.githubusercontent.com/68522810/191016012-6dce7f4d-7de0-4192-9194-b5359b74c0e2.png)
导入时显示无法导入，这种情况该怎么解决呢

**Comment by mh739025250** [comment]
你安装的delta-task具体是哪个版本呢？你pip list | grep delta-task看一下

**Comment by Dyson-c** [comment]
> 你安装的delta-task具体是哪个版本呢？grep delta-task 看一下

安装显示版本是0.1.2（如下图）
![image](https://user-images.githubusercontent.com/68522810/191151625-ef6132a5-9905-4698-b2a1-bb1fd25a64c9.png)
但是当指定安装版本，如0.5.0时，会显示如下错误（实际上我的虚拟环境就是torch1.8+cpu的）
![image](https://user-images.githubusercontent.com/68522810/191151696-5222239d-903f-4bac-9cd3-d83f9da3d37a.png)

**Comment by mh739025250** [comment]
0.1.2肯定是不可以的，建议安装0.6.0版本
torch的问题在于其cpu版本是不在pypi上的，所以你需要先安装指定版本的torch，再安装delta-task
目前delta-task的依赖的torch版本是1.8.2+cpu，建议去torch官网查看具体的安装命令

**Comment by Dyson-c** [comment]
> 0.1.2肯定是不可以的，建议安装0.6.0版本 torch的问题在于其cpu版本是不在pypi上的，所以你需要先安装指定版本的torch，再安装delta-task 目前delta-task的依赖的torch版本是1.8.2+cpu，建议去torch官网查看具体的安装命令

torch环境是通过pip 进行安装的，但是官网只有1.8.0和1.8.1版本的，没有1.8.2版本的可以拉取下载。然后通过尝试下载，还是报上面一样的错误
另外，delta-task包不支持GPU版本的torch吗？

**Comment by mh739025250** [comment]
![image](https://user-images.githubusercontent.com/7411300/191402463-80f6c654-1e42-470d-9ba1-ced78105a270.png)

**Comment by Dyson-c** [comment]
> ![image](https://user-images.githubusercontent.com/7411300/191402463-80f6c654-1e42-470d-9ba1-ced78105a270.png)

好的，那我如果强制更改setup.py的配置，进行安装torch gpu版本的，也是可以支持的吗

**Comment by mh739025250** [comment]
可以的
