### ISSUE TITLE
使用delta node API管理任务方法进行跑任务时，报错

### ISSUE THREAD

**Issue by Dyson-c** [delta-mpc/delta-task#14]
![image](https://user-images.githubusercontent.com/68522810/191401420-73320794-a5c5-4921-9b28-a2619b132229.png)

我使用的是all-in-one方法部署，但当使用delta-task包，进行外部idea编译时（跑 的代码是demo中的联邦统计），会报如上node的错误问题，请问这个该怎么解决？是不是需要额外单独再部署启动delta node呢？

**Comment by mh739025250** [comment]
你不能用这个DLETA_NODE_API，这个是deltaboard的api，你应该用delta-node的api
如果你是all-in-one部署的话，你需要修改docker-compose.yml文件，如下图所示：
![image](https://user-images.githubusercontent.com/7411300/191404399-3e4ad518-5776-4e7b-81c3-7f678a5e257f.png)
然后`DLETA_NODE_API = http://localhost:6700`

**Comment by Dyson-c** [comment]
> 你不能用这个DLETA_NODE_API，这个是deltaboard的api，你应该用delta-node的api 如果你是all-in-one部署的话，你需要修改docker-compose.yml文件，如下图所示： ![image](https://user-images.githubusercontent.com/7411300/191404399-3e4ad518-5776-4e7b-81c3-7f678a5e257f.png) 然后`DLETA_NODE_API = http://localhost:6700`

docker-compose.yml 是只改动node1这一处地方就可以了吗，我修改后，当进行up或者down时，就无法解析了，会报如下错误：
（docker重启也还是会这样报错）
![image](https://user-images.githubusercontent.com/68522810/191406466-a373eeaa-fc8b-4de9-8e59-eb6469e18d11.png)

**Comment by mh739025250** [comment]
你先down了之后再修改文件，再up，试一试

**Comment by Dyson-c** [comment]
> 你先down了之后再修改文件，再up，试一试
还是会报一样的错

**Comment by Dyson-c** [comment]
请问down了后修改文件，再up还是报一样的错，可以怎么解决呢

**Comment by mh739025250** [comment]
ports:
      - "6700:6700"
加上引号试试

**Comment by Dyson-c** [comment]
![image](https://user-images.githubusercontent.com/68522810/191458575-289373e0-59bc-4740-a27c-8f626b543d78.png)
加上引号就会显示数据格式不符合了

**Comment by mh739025250** [comment]
你docker-compose是什么版本的，我本地版本1.29.2，两种写法都不会报错

**Comment by Dyson-c** [comment]
冒号后面不加空格就可以正常up了。但是尝试编译的话，还是会出现如下问题
![image](https://user-images.githubusercontent.com/68522810/191461254-ba53daab-44af-48ac-82ca-60e46e784625.png)

**Comment by mh739025250** [comment]
你看一下node1镜像的日志

**Comment by mh739025250** [comment]
这个是运行过程中的错误，和这个issue没关系，建议开个新的issue
