### ISSUE TITLE
使用delta-task包进行外部idea编译时，会报错

### ISSUE THREAD

**Issue by Dyson-c** [delta-mpc/delta-task#15]
![image](https://user-images.githubusercontent.com/68522810/191464554-02ac0edf-bc9a-44bf-99b9-5a679e298126.png)
在使用外部idea进行编译横向联邦样例时，会出现如上的日志报错

**Comment by mh739025250** [comment]
把node1的日志贴出来看看

**Comment by Dyson-c** [comment]
贴的这个图就是node1的日志吧？

**Comment by mh739025250** [comment]
docker-compose logs -f node1

**Comment by Dyson-c** [comment]
![image](https://user-images.githubusercontent.com/68522810/191479120-06e7b96f-0a64-4392-8e78-1e8f41240d68.png)
![image](https://user-images.githubusercontent.com/68522810/191479202-4d763500-4356-4a7d-bf04-fe603d218bfd.png)

**Comment by mh739025250** [comment]
python版本不一致的问题，你创建任务时使用的python版本是3.9，在delta-node镜像内的python版本是3.8，在3.9版本pickle序列化的代码无法在3.8版本内执行。你可以把你创建任务的python版本降到3.8

**Comment by Dyson-c** [comment]
解决了，感谢
